### ISSUE TITLE
X axis?

### ISSUE THREAD

**Issue by mcrimi** [solgenomics/BrAPI-Study-Comparison#2]
Hi @dauglyon, 
How are you my friend?

I have a quick (and likely stupid) question: I think I understand what's represented in the Y axis (see screenshot) but it's not clear to me what's being represented in the X axis.

Thanks!!

![image](https://user-images.githubusercontent.com/1919014/49260288-8dbebe00-f402-11e8-8050-1963bb8bfeac.png)

**Comment by dauglyon** [comment]
Hi!

In the grid section, the x-axis and y-axis of each cell represent two different trials being compared. (So, each point is an accession, and it's x position is it's average in one trial and y is it's average in another; and each grid cell is two different trials being compared).

In the histogram section the x is the trait value and the y is  the raw count (the curves are kernel estimations of the distribution)

I'm not sure if that answers your question. Let me know
